baseURL = "https://hungryram.com/"
languageCode = "en-us"
summaryLength = 10
[[menu.main]]
name = "Customers"
url = "/customers"
weight = 5
[[menu.main]]
name = "Pricing"
url = "/pricing"
weight = 2
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 6
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 3
[taxonomies]
category = "categories"
project = "projects"
tag = "tags"
design = "designs"