baseURL = "https://hungryram.com/"
languageCode = "en-us"
summaryLength = 10
[[menu.main]]
name = "Custom Websites"
parent = "Websites"
url = "/jamstack-website-design"
weight = 2
[[menu.main]]
name = "Real Estate Websites"
parent = "Websites"
url = "/real-estate-websites"
weight = 1
[[menu.main]]
name = "Websites"
weight = 2
[[menu.main]]
name = "Customers"
url = "/customers"
weight = 5
[[menu.main]]
name = "Pricing"
url = "/pricing"
weight = 3
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 6
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 4
[taxonomies]
category = "categories"
design = "designs"
project = "projects"
tag = "tags"
